# Generated by Django 4.0 on 2024-01-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeowner',
            name='username',
        ),
    ]
