# Generated by Django 4.0 on 2024-01-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafeowner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cafeowner',
            name='last_name',
        ),
    ]
