# Generated by Django 4.0 on 2024-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_cafeowner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeowner',
            name='cafe_image',
            field=models.ImageField(default='default_image.jpg', upload_to='menu_images'),
        ),
    ]
