# Generated by Django 4.0 on 2024-01-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_cafeowner_email_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='cafe',
        ),
    ]
